/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_zhiliantiandi_twodtest_ScanLightController */

#ifndef _Included_com_zhiliantiandi_twodtest_ScanLightController
#define _Included_com_zhiliantiandi_twodtest_ScanLightController
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_zhiliantiandi_twodtest_ScanLightController
 * Method:    openDevice
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_zhiliantiandi_twodtest_ScanLightController_openDevice
  (JNIEnv *, jobject);

/*
 * Class:     com_zhiliantiandi_twodtest_ScanLightController
 * Method:    closeDevice
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_zhiliantiandi_twodtest_ScanLightController_closeDevice
  (JNIEnv *, jobject);

/*
 * Class:     com_zhiliantiandi_twodtest_ScanLightController
 * Method:    enableFloodLight
 * Signature: (Z)I
 */
JNIEXPORT jint JNICALL Java_com_zhiliantiandi_twodtest_ScanLightController_enableFloodLight
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_zhiliantiandi_twodtest_ScanLightController
 * Method:    enableLocationLight
 * Signature: (Z)I
 */
JNIEXPORT jint JNICALL Java_com_zhiliantiandi_twodtest_ScanLightController_enableLocationLight
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_zhiliantiandi_twodtest_ScanLightController
 * Method:    enableFlashLight
 * Signature: (Z)I
 */
JNIEXPORT jint JNICALL Java_com_zhiliantiandi_twodtest_ScanLightController_enableFlashLight
  (JNIEnv *, jobject, jboolean);

#ifdef __cplusplus
}
#endif
#endif
