/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <linux/ioctl.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <fcntl.h>
#include <android/log.h>

#define TAG "scanner"
#define LOGI(...) __android_log_print(ANDROID_LOG_INFO,TAG,__VA_ARGS__)
#define LOGD(...) __android_log_print(ANDROID_LOG_DEBUG, TAG, __VA_ARGS__)
#define LOGE(...) __android_log_print(ANDROID_LOG_ERROR,TAG,__VA_ARGS__)

#define CMD_FLAG  's'
#define SCAN_ON		_IOR(CMD_FLAG, 0x00000000, __u32)
#define SCAN_OFF	_IOR(CMD_FLAG, 0x00000001, __u32)

#define AIM_ON                      _IOR(CMD_FLAG, 0x00000003, __u32)
#define AIM_OFF                     _IOR(CMD_FLAG, 0x00000004, __u32)
#define ILLUM_ON                  _IOR(CMD_FLAG, 0x00000005, __u32)
#define ILLUM_OFF                  _IOR(CMD_FLAG, 0x00000006, __u32)
#define FLASHLIGHT_ON        _IOR(CMD_FLAG, 0x00000007, __u32)
#define FLASHLIGHT_OFF        _IOR(CMD_FLAG, 0x00000008, __u32)

#define SE955_CHANNEL_NAME "/dev/se955"
/* Header for class com_zhiliantiandi_twodtest_ScanLightController */

static int fd = -1;

#ifndef _Included_com_zhiliantiandi_twodtest_ScanLightController
#define _Included_com_zhiliantiandi_twodtest_ScanLightController
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     com_zhiliantiandi_twodtest_ScanLightController
 * Method:    openDevice
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_zhiliantiandi_twodtest_ScanLightController_openDevice(
		JNIEnv *env, jobject thiz) {
	fd = open(SE955_CHANNEL_NAME, O_RDWR);
	return fd;
}

/*
 * Class:     com_zhiliantiandi_twodtest_ScanLightController
 * Method:    closeDevice
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_zhiliantiandi_twodtest_ScanLightController_closeDevice(
		JNIEnv *env, jobject thiz) {
	int err = 0;
	err = close(fd);
	return err;
}

/*
 * Class:     com_zhiliantiandi_twodtest_ScanLightController
 * Method:    enableFloodLight
 * Signature: (Z)I
 */
JNIEXPORT jint JNICALL Java_com_zhiliantiandi_twodtest_ScanLightController_enableFloodLight(
		JNIEnv *env, jobject thiz, jboolean enable) {
	if(fd < 0) {
		return -1;
	}
	if(enable) {
		return ioctl(fd, ILLUM_ON);
	} else {
		return ioctl(fd, ILLUM_OFF);
	}
}

/*
 * Class:     com_zhiliantiandi_twodtest_ScanLightController
 * Method:    enableLocationLight
 * Signature: (Z)I
 */
JNIEXPORT jint JNICALL Java_com_zhiliantiandi_twodtest_ScanLightController_enableLocationLight(
		JNIEnv *env, jobject thiz, jboolean enable) {
	if(fd < 0) {
		return -1;
	}
	if(enable) {
		return ioctl(fd, AIM_ON);
	} else {
		return ioctl(fd, AIM_OFF);
	}
}
/*
 * Class:     com_zhiliantiandi_twodtest_ScanLightController
 * Method:    enableFlashLight
 * Signature: (Z)I
 */
JNIEXPORT jint JNICALL Java_com_zhiliantiandi_twodtest_ScanLightController_enableFlashLight
  (JNIEnv *env , jobject thiz, jboolean enable) {
	if(fd < 0) {
		return -1;
	}
	if(enable) {
		return ioctl(fd, FLASHLIGHT_ON);
	} else {
		return ioctl(fd, FLASHLIGHT_OFF);
	}
}

#ifdef __cplusplus
}
#endif
#endif
